apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-container
    image: demo:latest # Change to your image
    imagePullPolicy: Never # Prevents Kubernetes from trying to pull from Docker Hub
    ports:
    - containerPort: 8080
