apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 8080 # Container port
  type: LoadBalancer # For cloud environments (or use "NodePort")
